version: '3'
services:
  finorgDB:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "finorgDB"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./postgres-data:/var/lib/postgresql